version: "3"

services:

  rabbitmq:
      container_name: sensu-rabbitmq
      image: rabbitmq
      environment:
          - RABBITMQ_DEFAULT_USER=sensu
          - RABBITMQ_DEFAULT_PASS=password
          - RABBITMQ_DEFAULT_VHOST=/sensu

  redis:
      container_name: redis
      image: redis

  uchiwa:
      container_name: uchiwa
      image: uchiwa/uchiwa
      links:
          - api
      ports:
          - "3000:3000"
      volumes:
          - ./docker/uchiwa:/config

  server:
      container_name: sensu-server
      build: docker/server
      image: matthewfranglen/sensu-server
      links:
          - rabbitmq
          - redis

  api:
      container_name: sensu-api
      build: docker/api
      image: matthewfranglen/sensu-api
      links:
          - rabbitmq
          - redis

  client:
      container_name: sensu-client
      build: docker/client
      image: matthewfranglen/sensu-client
      links:
          - rabbitmq

  standalone_client:
      container_name: sensu-standalone-client
      build: docker/standalone-client
      image: matthewfranglen/sensu-standalone-client
      links:
          - rabbitmq
