version: "3"

services:

  rabbitmq:
      container_name: sensu-rabbitmq
      image: rabbitmq
      environment:
          - RABBITMQ_DEFAULT_USER=sensu
          - RABBITMQ_DEFAULT_PASS=password
          - RABBITMQ_DEFAULT_VHOST=/sensu

  redis:
      container_name: redis
      image: redis

  uchiwa:
      container_name: uchiwa
      image: uchiwa/uchiwa
      links:
          - api
      ports:
          - "3000:3000"
      volumes:
          - ./docker/uchiwa:/config

  server:
      container_name: sensu-server
      build: docker/server
      image: matthewfranglen/sensu-server
      links:
          - rabbitmq
          - redis

  api:
      container_name: sensu-api
      build: docker/api
      image: matthewfranglen/sensu-api
      links:
          - rabbitmq
          - redis

  client-1:
      container_name: sensu-client-1
      build:
        context: docker/client
        args:
          - "ID=1"
      links:
          - rabbitmq

  client-2:
      container_name: sensu-client-2
      build:
        context: docker/client
        args:
          - "ID=2"
      links:
          - rabbitmq

  client-3:
      container_name: sensu-client-3
      build:
        context: docker/client
        args:
          - "ID=3"
      links:
          - rabbitmq

  client-4:
      container_name: sensu-client-4
      build:
        context: docker/client
        args:
          - "ID=4"
      links:
          - rabbitmq

  standalone_client:
      container_name: sensu-standalone-client
      build: docker/standalone-client
      image: matthewfranglen/sensu-standalone-client
      links:
          - rabbitmq
